import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '../fontawesome';

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { WishlistProvider } from "./Category/context/WishlistContext";
import { CartProvider } from "./Category/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          <WishlistProvider>
            <Navbar />
            <div className="pt-10 bg-white">
              {children}
            </div>
            <Footer />
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
